name: Docker Build and Push

on:
  push:
    branches:
      - estimation-jayadeepikakoppineni-20240131

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image
        run: |
          cd crew_manual
          docker build -t deepika1924/my-astro-app .
      - name: Log in to Docker Hub
        run: docker login -u deepika1924 -p Dipika@3235

      - name: Push Docker image
        run: docker push deepika1924/my-astro-app
      
      - name: Run Docker container
        run: docker run -d -p 4321:3000 deepika1924/my-astro-app;