# .github/workflows/ci.yml

name: CI

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build containers
      run: docker-compose up -d
    - name: Test
      run: curl localhost:8080