version: '3'
services:
  your-service:
    image: docker/welcome-to-docker:latest
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - /path/to/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    # Other production-specific configurations
