name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: #software image#
        ports:
          - 3000:3000
        options: --entrypoint /usr/bin/dockerd-entrypoint.sh

    steps:
    - name: Checkout code
      uses: #path code#
    - name: Build and test
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose exec app npm test
