services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code

  test:
    build: .
    command: ["pytest", "app_test.py"]
    volumes:
      - .:/code  # Mount current directory for accessing app and app_test.py

  redis:
    image: "redis:alpine"