version: "3"
services:
  app:
    image: your-app-image
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=your_database
      - POSTGRES_USER=akurapati1
      - POSTGRES_PASSWORD=Abhilasya@1