version: '3.8'
services:
  dockerpractice-psd:
    image: dockerpracticee:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
