version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    restart: always
    environment:
      - FLASK_ENV=production

  redis:
    image: "redis:alpine"
    restart: always