name: Docker Build and Push

on:
  push:
    branches:
      - estimation-github-suprajamannava17-20240130

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image
        run: |
          cd crew_manual
          docker build -t suprajamannava/my-app .
      - name: Log in to Docker Hub
        run: docker login -u suprajamannava -p Supraja@17

      - name: Push Docker image
        run: docker push suprajamannava/my-app
      
      - name: Run Docker container
        run: docker run -d -p 4321:3000 suprajamannava/my-app;