name: CI/CD Pipeline

on:
  push:
    branches:
      - estimation-github-Abhi-Stephen-240131

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Code linting
        run: |
          pylint main.py
