name: CI/CD Pipeline

on:
  push:
    branches:
      - estimation-github-Pranithapadala-240131
  pull_request:
    branches:
    - estimation-github-Pranithapadala-240131
  
      

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      #- name: Code Linting
       # run: npm run lint
