name: CI/CD Pipeline

on:
  push:
    branches:
      - estimation-github-nani1606-20240130
  pull_request:
    branches:
      - estimation-github-nani1606-20240130

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint