name: CI/CD Pipeline

on:
  push:
    branches:
      - estimation-github-yrlmanoharreddy-240131

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11'

      - name: Install dependencies
        run: npm install

      - name: Build site with Astro
        run: npm run build

      - name: Run linting
        run: npm run lint
