name: Docker Build and Push

on:
  push:
    branches:
      - estimation-sai-gif-240130

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker --version

      - name: Build Docker image
        run: |
          cd crew_manual
          docker build -t saikumarreddy081/my-astro-app .
      - name: Log in to Docker Hub
        run: docker login -u saikumarreddy081 -p HavefunHavefun1!1!

      - name: Push Docker image
        run: docker push saikumarreddy081/my-astro-app
      
      - name: Run Docker container
        run: docker run -d -p 4321:3000 saikumarreddy081/my-astro-app;
