name: Docker Build and Push

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:21.6.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo service docker start
          sudo usermod -aG docker $USER
          docker --version
          docker info

      - name: Build Docker image
        run: |
          cd crew_manual  # Change to the directory with your Dockerfile
          docker build -t vineeth0502/your-astro-app .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push vineeth0502/your-astro-app
